name: PlotVote
main: wortie\PlotVote\PlotVote
version: 1.3.0
api: 3.12.0
mcpe-protocol: [389, 390]
load: POSTWORLD
author: wortie
website: https://www.newcrestmc.net/
description: This Plugin was designed for Creative/Plots Servers to rate a players plot.
depend: MyPlot
commands:
 plotvote:
  description: "Upvote a plot"
  usage: "/plotvote"
  permission: plotvote.command
 pv:
  permission: plotvote.command.pv
  usage: "/pv <top|info|setlb|remlb>"
permissions:
 plotvote.command.lb:
  default: op
 plotvote:
  default: true
  description: "PlotVote Root Node"
  children:
   plotvote.command:
    default: true
    description: "Allows the use of /plotvote"
   plotvote.command.pv:
    default: true
